name: kg_EnchantScroll_Weapon_Blessed_S
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Coins:600:0:True
- BlackCore:5:0:True
- JuteBlack_TW:10:0:True
- kg_EnchantScroll_Weapon_S:1:0:True
