name: kg_EnchantScroll_Armor_B
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- GrizzlyBearPelt_TW:5:0:True
- FreezeGland:5:0:True
- InfusedCrystal_JH:2:0:True
- TrophyHatchling:1:0:True
