name: kg_EnchantScroll_Armor_Blessed_A
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Coins:500:0:True
- LoxBone_TW:5:0:True
- InfusedCrystal_JH:20:0:True
- kg_EnchantScroll_Armor_A:1:0:True
