name: kg_EnchantScroll_Armor_Blessed_B
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Coins:400:0:True
- WolfHairBundle:5:0:True
- InfusedCrystal_JH:20:0:True
- kg_EnchantScroll_Armor_B:1:0:True
