name: kg_EnchantScroll_Armor_S
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Eitr:5:0:True
- VenomousFang_TW:5:0:True
- InfusedCrystal_JH:2:0:True
- TrophySeeker:1:0:True
