name: Sapling_MushroomWitcheye_TW
piecehammer: Cultivator
m_name: $consume_witcheye_TW
sizeMultiplier: 1
m_description: ''
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: ''
piecehammerCategory: Misc
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: false
notOnWood: false
wearNTearData: 
craftingStationData: 
cSExtensionData: 
contData: 
smelterData: 
cookingStationData: 
beehiveData: 
fermStationData: 
sapData: 
incineratorData: 
fireplaceData: 
teleportWorldData: 
plantData:
  m_name: $sapling_witcheye_TW
  GrowTime: 4000
  MaxGrowTime: 5000
  GrowPrefab: Pickable_GrownMushroomWitcheye_TW
  MinSize: 0.8
  MaxSize: 1.1
  GrowRadius: 0.5
  GrowRadiusVines: 0
  CultivatedGround: true
  DestroyIfCantGrow: true
  TolerateHeat: false
  TolerateCold: false
  Biomes: -1
build:
- MushroomWitcheye_TW:1:1:False
- BoneFragments:1:1:False