name: Chain
clonePrefabName: Chain
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrophyWraith:1:1:True
