name: Guck
clonePrefabName: Guck
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 2
disabled: false
requireOnlyOneIngredient: true
reqs:
- TrophyBlob:1:1:True
- TrophyRottingElk_TW:1:1:True
- TrophyCrawler_TW:1:1:True
