name: DeerHide
clonePrefabName: DeerHide
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrophyDeer:1:1:True
