name: TrollBone_TW
clonePrefabName: TrollBone_TW
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrophyFrostTroll:1:1:True
