Name: SE_RogueIron_TW
Status_m_name: $rogueset_TW
Category: ''
IconName: HelmetRotten_TW276 666
ClonedSE: 
CustomIcon: 
FlashIcon: false
CooldownIcon: false
Tooltip: $ironrogueset_description_TW
Attributes: None
StartMessageLoc: TopLeft
StartMessage: ''
StopMessageLoc: TopLeft
StopMessage: ''
RepeatMessageLoc: TopLeft
RepeatMessage: ''
RepeatInterval: 0
TimeToLive: 0
StartEffect_: 
StopEffect_: 
StartEffect_PLUS: []
StopEffect_PLUS: []
Cooldown: 0
ActivationAnimation: gpower
SeData:
  m_tickInterval: 0
  m_healthPerTickMinHealthPercentage: 0
  m_healthPerTick: 0
  m_healthOverTime: 0
  m_healthOverTimeDuration: 0
  m_healthOverTimeInterval: 0
  m_staminaOverTime: 0
  m_staminaOverTimeDuration: 0
  m_staminaDrainPerSec: 0
  m_runStaminaDrainModifier: -0.1
  m_jumpStaminaUseModifier: -0.1
  m_eitrOverTime: 0
  m_eitrOverTimeDuration: 0
  m_healthRegenMultiplier: 1
  m_staminaRegenMultiplier: 1.06
  m_eitrRegenMultiplier: 1
  m_raiseSkill: None
  m_raiseSkillModifier: 0
  m_skillLevel: Knives
  m_skillLevelModifier: 20
  m_skillLevel2: None
  m_skillLevelModifier2: 0
  m_mods: []
  m_modifyAttackSkill: Knives
  m_damageModifier: 1.04
  m_noiseModifier: 0
  m_stealthModifier: 0
  m_addMaxCarryWeight: 0
  m_speedModifier: 0
  m_jumpModifier: &o0
    x: 0
    y: 0
    z: 0
    normalized: *o0
    magnitude: 0
    sqrMagnitude: 0
  m_maxMaxFallSpeed: 0
  m_fallDamageModifier: 0
  m_tickTimer: 0
  m_healthOverTimeTimer: 0
  m_healthOverTimeTicks: 0
  m_healthOverTimeTickHP: 0
SeShield: 
