name: WarpikeElder1
clonePrefabName: WarpikeElder_TW
craftingStation: $piece_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $piece_forge
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- ElderBark:0:16:True
- Bronze:20:12:True
- AncientSeed:4:2:True
- TrophyTheElder:1:1:True
- InfusedCrystal_JH:20:0:True
