name: Recipe_Defender_Legs_Iron_LG
clonePrefabName: Defender_Legs_Iron_LG
craftingStation: $piece_armory_TW
minStationLevel: 2
maxStationLevelCap: 4
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- ArmorIronLegs:1:0:True
- Iron:12:12:True
- Bronze:10:6:True
- Guck:10:8:True
