name: mmo_mead_orb6
clonePrefabName: mmo_mead_orb6
craftingStation: $piece_cauldron
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- DustMagic:5:0:True
- InfusedCrystal_JH:10:0:True
- MeadTasty:2:0:True
- TrophyDvergr:1:0:True
