name: mmo_mead_orb1
clonePrefabName: mmo_mead_orb1
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- DustMagic:5:0:True
- InfusedCrystal_JH:10:0:True
- MeadTasty:2:0:True
- TrophyFox_TW:1:0:True
