Name: SetEffect_DvergrBelt
Status_m_name: Dvergr Belt
Category: ''
IconName: 
CustomIcon: BeltStrength.png
FlashIcon: false
CooldownIcon: false
Tooltip: $se_beltstrength_tooltip
Attributes: None
StartMessageLoc: Center
StartMessage: $se_beltstrength_start
StopMessageLoc: TopLeft
StopMessage: ''
RepeatMessageLoc: TopLeft
RepeatMessage: ''
RepeatInterval: 0
TimeToLive: 0
StartEffect: []
StopEffect: []
Cooldown: 0
ActivationAnimation: gpower
SeData:
  m_tickInterval: 0
  m_healthPerTickMinHealthPercentage: 0
  m_healthPerTick: 0
  m_healthOverTime: 0
  m_healthOverTimeDuration: 0
  m_healthOverTimeInterval: 5
  m_staminaOverTime: 0
  m_staminaOverTimeDuration: 0
  m_staminaDrainPerSec: 0
  m_runStaminaDrainModifier: 0
  m_jumpStaminaUseModifier: 0
  m_eitrOverTime: 0
  m_eitrOverTimeDuration: 0
  m_healthRegenMultiplier: 1
  m_staminaRegenMultiplier: 1
  m_eitrRegenMultiplier: 1
  m_raiseSkill: None
  m_raiseSkillModifier: 0
  m_skillLevel: None
  m_skillLevelModifier: 0
  m_skillLevel2: None
  m_skillLevelModifier2: 0
  m_mods: []
  m_modifyAttackSkill: None
  m_damageModifier: 1
  m_noiseModifier: 0
  m_stealthModifier: 0
  m_addMaxCarryWeight: 250
  m_speedModifier: 0
  m_maxMaxFallSpeed: 0
  m_fallDamageModifier: 0
  m_tickTimer: 
  m_healthOverTimeTimer: 
  m_healthOverTimeTicks: 
  m_healthOverTimeTickHP: 
