name: CookedSpiderMeat
m_weight: 1
m_name: Cooked Spider Meat
m_description:  cooked spider meat that should be ok to eat?
clonePrefabName: ScorpidMeat_TW
mockName: 
customIcon: 
material: Meat_Cooked
customVisual: 
sizeMultiplier: 0.75
scale_weight_by_quality: 0
FoodStats:
  m_foodHealth: 32
  m_foodStamina: 15
  m_foodRegen: 2
  m_foodBurnTime: 1200
  m_FoodEitr: 0
m_maxStackSize: 20
m_canBeReparied: true
m_destroyBroken: true
m_dodgeable: false
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 4
m_knockback: 50
m_useDurability: false
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 100
m_durabilityPerLevel: 50
m_equipDuration: 1
m_skillType: Swords
m_animationState: OneHanded
m_itemType: Consumable
m_toolTier: 0
m_maxQuality: 1
m_value: 0
ConsumableStatusEffect: SE_CookedSpiderMeat
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect: 
  Trail_Effect: 
