name: BlackMetalBelt_JH
m_weight: 2
m_name: BlackMetal Belt
m_description: Gives the wearer extra superhuman strength +200 Weight
clonePrefabName: BeltYmir_TW
mockName: 
customIcon: 
material: blackmetal
customVisual: 
sizeMultiplier: 1
scale_weight_by_quality: 0
SE_Equip:
  EffectName: SetEffect_BlackMetalBelt
SE_SET_Equip: 
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: true
m_dodgeable: false
Attack_status_effect: 
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 4
m_knockback: 50
m_useDurability: false
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 100
m_durabilityPerLevel: 50
m_equipDuration: 2
m_skillType: Swords
m_animationState: OneHanded
m_itemType: Utility
m_toolTier: 0
m_maxQuality: 1
m_value: 0
damageModifiers: []
GEffects:
  Hit_Effects: 
  Hit_Terrain_Effects: 
  Start_Effect: 
  Hold_Start_Effects: 
  Trigger_Effect: 
  Trail_Effect: 
