name: ShardQueen_TW
clonePrefabName: ShardQueen_TW
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 6
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Eitr:5:0:True
- DarkCrystal_TW:2:0:True
- TrophyDvergr:1:0:True
