name: ShardBonemass_TW
clonePrefabName: ShardBonemass_TW
craftingStation: $piece_arcaneanvil_TW
minStationLevel: 3
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
upgrade_reqs: []
reqs:
- Iron:5:0:True
- WitheredBone:2:0:True
- TrophySkeletonPoison:1:0:True
