name: Custom_BlackForge_Ext_1
piecehammer: Hammer
m_name: $custom_blackforge_ext_1
sizeMultiplier: 1
m_description: $custom_blackforge_ext_1_description
customIcon: 
clonePrefabName: 
material: 
damagedMaterial: 
craftingStation: $piece_blackforge
piecehammerCategory: Crafting
minStationLevel: 1
amount: 1
disabled: false
adminonly: false
comfort: 
groundPiece: false
ground: false
waterPiece: false
noInWater: true
notOnFloor: false
onlyinTeleportArea: false
allowedInDungeons: false
canBeRemoved: true
wearNTearData:
  health: 100
  damageModifiers:
    m_blunt: Normal
    m_slash: Normal
    m_pierce: Resistant
    m_chop: Weak
    m_pickaxe: Normal
    m_fire: Normal
    m_frost: Resistant
    m_lightning: Normal
    m_poison: Immune
    m_spirit: Immune
  noRoofWear: true
  noSupportWear: true
  supports: false
  triggerPrivateArea: true
craftingStationData: 
cSExtensionData:
  MainCraftingStationName: blackforge
  maxStationDistance: 5
  continousConnection: false
  stack: false
contData: 
smelterData: 
cookingStationData: 
build:
- Iron:10:1:True
- BlackMarble:10:1:True
- BlackCore:2:1:True
