- Items:
  - PickaxeAntler
  - PickaxeBronze
  - PickaxeIron
  - PickaxeSilver_TW
  - PickaxeBlackMetal
  - PickaxeFader_TW
  Stats:
    1:
      damage_percentage: 2
      damage_pickaxe: 2
    2:
      damage_percentage: 4
      damage_pickaxe: 3
    3:
      damage_percentage: 6
      damage_pickaxe: 4
    4:
      damage_percentage: 8
      damage_pickaxe: 5
    5:
      damage_percentage: 10
      damage_pickaxe: 10
    6:
      damage_percentage: 12
      damage_pickaxe: 11
    7:
      damage_percentage: 16
      damage_pickaxe: 12
    8:
      damage_percentage: 20
      damage_pickaxe: 13
    9:
      damage_percentage: 24
      damage_pickaxe: 14
    10:
      damage_percentage: 28
      damage_pickaxe: 15
    11:
      damage_percentage: 32
      damage_pickaxe: 16
    12:
      damage_percentage: 36
      damage_pickaxe: 17
    13:
      damage_percentage: 40
      damage_pickaxe: 18
    14:
      damage_percentage: 45
      damage_pickaxe: 19
    15:
      damage_percentage: 50
      damage_pickaxe: 20
    16:
      damage_percentage: 55
      damage_pickaxe: 25
    17:
      damage_percentage: 60
      damage_pickaxe: 30
    18:
      damage_percentage: 70
      damage_pickaxe: 35
    19:
      damage_percentage: 85
      damage_pickaxe: 40
    20:
      damage_percentage: 100
      damage_pickaxe: 50