name: HoneyGlazedWolf
clonePrefabName: HoneyGlazedWolf
craftingStation: $piece_cauldron
minStationLevel: 3
maxStationLevelCap: 
repairStation: $piece_workbench
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- CookedWolfMeat:1:1:True
- Honey:2:1:True
