name: SurtlingCore
clonePrefabName: SurtlingCore
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- TrophySurtling:1:1:True
