name: WolfFang
clonePrefabName: WolfFang
craftingStation: $custom_sky_forge
minStationLevel: 1
maxStationLevelCap: 
repairStation: $custom_sky_forge
amount: 2
disabled: false
requireOnlyOneIngredient: true
reqs:
- TrophyWolf:1:1:True
- TrophyUlv:1:1:True
