PrintComment: ThisGoesHere is moving edited files
CopyFolder:
- From: config\_RelicHeimFiles\RandyKnapp-EpicLoot\
  To: plugins\
CopyFile:
- From: config\_RelicHeimFiles\ThisGoesHereMovedFile\English.yml
  To: plugins\Smoothbrain-CreatureLevelAndLootControl\English.yml
- From: config\_RelicHeimFiles\ThisGoesHereMovedFile\Russian.yml
  To: plugins\Smoothbrain-CreatureLevelAndLootControl\Russian.yml
- From: config\_RelicHeimFiles\ThisGoesHereMovedFile\MonsterLabZ.cfg
  To: config\MonsterLabZ.cfg