name: rae_Horseaker
m_weight: 2.5
m_name: $horseaker
m_description: $horseaker_desc
clonePrefabName: 
mockName: 
customIcon: 
material: 
materials: 
customVisual: 
snapshotRotation: 
snapshotOnMaterialChange: true
sizeMultiplier: 1
scale_weight_by_quality: 0
Primary_Attack:
  AttackType: Horizontal
  Attack_Animation: battleaxe_attack
  Attack_Random_Animation: 0
  Chain_Attacks: 3
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 16
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  DmgMultiplier: 1
  ForceMultiplier: 1
  StaggerMultiplier: 1.5
  RecoilMultiplier: 0
  AttackRange: 2.7
  AttackHeight: 1
  Spawn_On_Trigger: 
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime: 2
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain: 0
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 120
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: false
  Hit_Through_Walls: true
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: Tree
  SpawnOnHit: 
  SpawnOnHit_Chance: 0
  Attack_status_effect: 
  Attack_status_effect_chance: 
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: WoodCutting
  Special_Hit_Type: Tree
  Attack_Projectile: 
  Projectile_Vel: 20
  Projectile_Accuraccy: 0
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects: 
  AEffectsPLUS:
    Hit_Effects: []
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Secondary_Attack:
  AttackType: Vertical
  Attack_Animation: swing_sledge
  Attack_Random_Animation: 0
  Chain_Attacks: 0
  Hit_Terrain: true
  Custom_AttackSpeed: 1
  m_attackStamina: 18
  m_eitrCost: 0
  AttackHealthCost: 0
  m_attackHealthPercentage: 0
  SpeedFactor: 0.3
  DmgMultiplier: 4
  ForceMultiplier: 1
  StaggerMultiplier: 2
  RecoilMultiplier: 0
  AttackRange: 3
  AttackHeight: 1
  Spawn_On_Trigger:
  Requires_Reload: false
  Reload_Animation: ''
  ReloadTime:
  ReloadTimeMultiplier: 1
  Reload_Stamina_Drain: 0
  Reload_Eitr_Drain:
  Bow_Draw: false
  Bow_Duration_Min: 0
  Bow_Stamina_Drain: 0
  Bow_Animation_State: ''
  Attack_Angle: 30
  Attack_Ray_Width: 0.5
  Lower_Dmg_Per_Hit: true
  Hit_Through_Walls: false
  Multi_Hit: true
  Pickaxe_Special: false
  Last_Chain_Dmg_Multiplier: 2
  Reset_Chain_If_hit: None
  SpawnOnHit:
  SpawnOnHit_Chance: 0
  Attack_status_effect:
  Attack_status_effect_chance:
  Raise_Skill_Amount: 1
  Skill_Hit_Type: Character
  Special_Hit_Skill: None
  Special_Hit_Type: None
  Attack_Projectile:
  Projectile_Vel: 10
  Projectile_Accuraccy: 10
  Projectiles: 1
  Skill_Accuracy: false
  Launch_Angle: 0
  Projectile_Burst: 1
  Burst_Interval: 0
  Destroy_Previous_Projectile: false
  PerBurst_Resource_usage: false
  Looping_Attack: false
  Consume_Item: false
  AEffects:
  AEffectsPLUS:
    Hit_Effects: []
    Hit_Terrain_Effects: []
    Start_Effect: []
    Trigger_Effect: []
    Trail_Effect: []
    Burst_Effect: []
Damage:
  Blunt: 0
  Chop: 50
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 75
  Spirit: 0
Damage_Per_Level:
  Blunt: 0
  Chop: 7
  Damage: 0
  Fire: 0
  Frost: 0
  Lightning: 0
  Pickaxe: 0
  Pierce: 0
  Poison: 0
  Slash: 6
  Spirit: 0
Armor:
  armor: 15
  armorPerLevel: 1
FoodStats: 
Moddifiers:
  m_movementModifier: -0.1
  m_EitrRegen: 0
  m_homeItemsStaminaModifier: 0
  m_heatResistanceModifier: 0
  m_jumpStaminaModifier: 0
  m_attackStaminaModifier: 0
  m_blockStaminaModifier: 0
  m_dodgeStaminaModifier: 0
  m_swimStaminaModifier: 0
  m_sneakStaminaModifier: 0
  m_runStaminaModifier: 0
SE_Equip: 
SE_SET_Equip:
  SetName: Horseaker
  Size: 3
  EffectName: SetEffect_HorseJarl
ShieldStats:
  m_blockPower: 66
  m_blockPowerPerLevel: 0
  m_timedBlockBonus: 3
  m_deflectionForce: 72
  m_deflectionForcePerLevel: 4
m_maxStackSize: 1
m_canBeReparied: true
m_destroyBroken: false
m_dodgeable: true
Attack_status_effect: 
Attack_status_effect_chance: 1
spawn_on_hit: 
spawn_on_terrain_hit: 
m_questItem: false
m_teleportable: true
m_backstabbonus: 4
m_knockback: 70
m_useDurability: true
m_useDurabilityDrain: 1
m_durabilityDrain: 0
m_maxDurability: 200
m_durabilityPerLevel: 50
m_equipDuration: 0.2
Attach_Override: None
m_skillType: Axes
m_animationState: TwoHandedAxe
m_itemType: TwoHandedWeapon
m_toolTier: 3
m_maxQuality: 10
m_value: 0
ConsumableStatusEffect: 
damageModifiers: []
GEffects: 
GEffectsPLUS:
  Hit_Effects:
  - name: vfx_clubhit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: sfx_battleaxe_hit
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  - name: fx_hit_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Hit_Terrain_Effects: []
  Start_Effect: []
  Hold_Start_Effects: []
  Trigger_Effect:
  - name: fx_swing_camshake
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
  Trail_Effect:
  - name: sfx_battleaxe_swing_wosh
    m_enabled: true
    m_variant: -1
    m_attach: false
    m_follow: false
    m_inheritParentRotation: false
    m_inheritParentScale: false
    m_multiplyParentVisualScale: false
    m_randomRotation: false
    m_scale: false
    m_childTransform: ''
