name: HoneyGlazedNeck
clonePrefabName: HoneyGlazedNeck
craftingStation: $piece_workbench
minStationLevel: 2
maxStationLevelCap: 
repairStation: $piece_workbench
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- NeckTailGrilled:1:1:True
- Honey:2:1:True
