name: SpiderMeatSkewer_JH
clonePrefabName: SpiderMeatSkewer_JH
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- SpiderMeat:1:1:True
- Mushroom:2:1:True
- Carrot:1:1:True
