name: ElkJerky
clonePrefabName: ElkJerky
craftingStation: $piece_cauldron
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- RottingElkMeat_TW:1:1:True
- Honey:1:1:True
- Coal:5:1:True
