name: LoxJerky_JH
clonePrefabName: LoxJerky_JH
craftingStation: $piece_cauldron
minStationLevel: 4
maxStationLevelCap: 
repairStation: 
amount: 2
disabled: false
requireOnlyOneIngredient: false
reqs:
- LoxMeat:1:1:True
- Honey:2:1:True
- Cloudberry:1:1:True
