name: ArmorPaddedCuirass
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- BlackMetal:20:5:True
- GoblinScraps_TW:10:5:True
- LinenThread:20:10:True
