English:
  ArmorNobleHelmet: Kylfing hat
  ArmorNobleHelmet_description: Fashionable hat with fur lining, you look like a twat that poses no threat!
  ArmorNobleChest: Kylfing garb
  ArmorNobleChest_description: A garb stitched together from banners torn from your burial chamber, a good alternative to sprinting around Vanaheim bare.
  ArmorNobleLegs: Kylfing pants
  ArmorNobleLegs_description: Worn, loose pants, perfect for running away from danger!
  ArmorNobleCape: Vegvisir cape
  ArmorNobleCape_description: The magic of the vegvisir enhances your speed.
  ArmorBarbarianBronzeHelmetJD: Barbarian helmet
  ArmorBarbarianBronzeHelmetJD_description: A barbaric helmet made from a metal alloy.
  ArmorBarbarianBronzeChestJD: Barbarian armor
  ArmorBarbarianBronzeChestJD_description: A metal disc attached to pelts, a true axezerker hurls himself into battle despite the lack of protection.
  ArmorBarbarianBronzeLegsJD: Barbarian pants
  ArmorBarbarianBronzeLegsJD_description: Thick pelts wrapped around one's waist, fastened with a fashionable belt.
  ArmorBarbarianCapeJD: Berserker cape
  ArmorBarbarianCapeJD_description: Thick, short cape made from fur. Covers ones back when his drunk raidmates can't.
  ArmorWarriorHelmet: Brokkr chainmail
  ArmorWarriorHelmet_description: A thick metal chainmail to protect you from blows but lacks protection from being stabbed.
  ArmorWarriorChest: Brokkr hauberk
  ArmorWarriorChest_description: Chainmail vest adorned with runes of courage to boost the spirit.
  ArmorWarriorLegs: Brokkr boots
  ArmorWarriorLegs_description: Leather pelts and chains sewn to keep it's wearer warm and protected.
  ArmorPlateIronHelmetJD: Vanguard helmet
  ArmorPlateIronHelmetJD_description: A sturdy metal plate helmet with a leather neckguard.
  ArmorPlateIronChestJD: Vanguard cuirass
  ArmorPlateIronChestJD_description: Thick plates of metal riveted to a leather harness to protect you from harms way, but if doused in poison you'll be sorry.
  ArmorPlateIronLegsJD: Vanguard greaves
  ArmorPlateIronLegsJD_description: Reliable greaves and kneeguards made out of metal and leather.
  ArmorPlateCape: Salamander cape
  ArmorPlateCape_description: Cape made to protect against dangerous situations.
  ArmorDragonslayerHelmet: Niddhog horns
  ArmorDragonslayerHelmet_description: Dragon's tremble in fear when they see the blackened helmet adorned with the horns of their kin.
  ArmorDragonslayerChest: Niddhog armor
  ArmorDragonslayerChest_description: plates of silver sewn on wolf hides.
  ArmorDragonslayerLegs: Niddhog greaves
  ArmorDragonslayerLegs_description: Unlucky is he who finds himself in the way of these.
  ArmorWandererHelmet: Ulfberht hat
  ArmorWandererHelmet_description: A traditional monk's metal reinforced hat.
  ArmorWandererChest: Ulfberht armor
  ArmorWandererChest_description: Small metal plates attached to a leather jerkin, easy to maintain during travels but easy to get gashed
  ArmorWandererLegs: Ulfberht pants
  ArmorWandererLegs_description: Durable pants with makeshift metal protection around the shins.
  ArmorWandererCape: Wanderer's cape
  ArmorWandererCape_description: Protects against toxic bitches.
  ArmorBlackmetalgarbHelmet: Rhovanion helmet
  ArmorBlackmetalgarbHelmet_description: Metal helmet with colorful padding fit for a true Rhovanion.
  ArmorBlackmetalgarbChest: Rhovanion garb
  ArmorBlackmetalgarbChest_description: A nomadic garb adorned with protective elements made from leathers and metal.
  ArmorBlackmetalgarbLegs: Rhovanion boots
  ArmorBlackmetalgarbLegs_description: Thick leather boots with a metal toe guard.
  ArmorSerpentHelmet: Jormungandr helmet
  ArmorSerpentHelmet_description: A thick metal casque adorned by the fins of a mighty serpent. The style is popular with raiding knights of the North.
  ArmorSerpentChest: Jormungandr armor
  ArmorSerpentChest_description: Plates of metal overtop a surcoat of sea serpent scales. The perfect garb for spreading Odin's good word but lacks protection from heat
  ArmorSerpentLegs: Jormungandr cuisses
  ArmorSerpentLegs_description: Metal cuisses, greaves and sabatons, excellent protection with a slightly fishy smell.
  ArmorSerpentCape: Jormungandr knight's Cape
  ArmorSerpentCape_description: Heavy dark cape of the Serpent order.
  ArmorMistlandsHelmet: Ragnarok sallet
  ArmorMistlandsHelmet_description: Protective helmet that guards the face.
  ArmorMistlandsChest: Ragnarok armor
  ArmorMistlandsChest_description: Thick, multi layered gambeson provides protection from fatal blows...almost
  ArmorMistlandsLegs: Ragnarok greaves
  ArmorMistlandsLegs_description: One knows how to dance the dance of the death with these.
  BackpackSimple: Simple Backpack
  BackpackSimple_description: Leather container attached to a wooden frame.
  BackpackHeavy: Heavy Backpack
  BackpackHeavy_description: Large chest hauled on ones shoulders with a canvas bag for additional storage.

