name: sm_base_greaterhealth
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 5
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- MeadTasty:3:0:False
- GiantBloodSack:5:0:False
- RoyalJelly:10:0:False
