name: sm_base_exp
clonePrefabName: 
craftingStation: $piece_cauldron
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: true
requireOnlyOneIngredient: false
reqs:
- MeadTasty:3:0:False
- Thunderstone:10:0:False
- Thistle:5:0:False
- Honey:10:0:False
