# You can add your own texts here.
# No, you cannot add your own categories.
# Don't use very long texts.

general:
 - "{player} снова решил выделиться – умер не так, как все. Может, следующий раз он попробует обычный вариант, чтобы нас удивить?"
 - "И вот {player} снова на вершине оригинальности, уходя из этого мира необычным способом. Видимо, обычные смерти – слишком банально."
 - "Представляем вам {player}, который ушел в мир иной, предпочтя необычный путь. Мы все ждем, когда он вернется и расскажет, как там."
 - "В очередной раз {player} доказал, что обычное – это не для него. Умер, оставив нас в недоумении и вопросами. Кто-то у нас тут любит загадки."

death by fire:
- "Пламя приняло в свои объятия {player}, и вот он ушел, оставив нас в тени его горящих подвигов."
- "В огненном танце {player} нашел свой последний аккорд. Кто знал, что огонь так хорош в музыкальном сопровождении?"
- "Сегодня мы прощаемся с {player}, который предпочел уходить, окруженный атмосферой пылающего арены. Всегда на высоте!"
- "Огонь стал финальным испытанием для {player}. Поздравляем, теперь он настоящий огненный воин."
- "Оказывается, {player} не огнеупорен. Кто бы мог подумать? Ах да, все, кроме него."
- "Похоже, {player} перепутал 'тёплый' с 'обжаренный'. Теперь Вальхалла наслаждается ароматом поджаренного героя."
- "Теперь все знают, что {player} — не только герой, но и отличное топливо для костра."
- "Вальхалла аплодирует {player} за храбрость... и за то, что он доказал: огонь — лучший способ быстро стать легендой."
- "Один наблюдал за подвигом {player} и подумал: 'Смелость у него есть, а вот огнезащита — не очень'."
- "Теперь Вальхалла вспоминает {player} как героя, который горел слишком ярко... буквально."

death by poison:
- "{player} попробовал на вкус тот самый яд – необычный выбор для завершения приключения. Приятного аппетита!"
- "Смерть от яда? {player} действительно находит новые способы завершения игры. В следующий раз, наверное, он выберет что-то менее токсичное."
- "В этот раз {player} решил, что уж лучше пусть его проглотит яд, чем он сам будет глотать поражения. Каждый выбирает свой путь к победе, не так ли?"
- "Смерть от яда стала финальным аккордом приключений {player}. Кто бы мог подумать, что яд может быть таким креативным в руках игрока?"


death by frost:
- "В объятиях холода {player} нашел свой последний покой. Замерзший герой, легенда в льду – так закончилась их история."
- "Ледяные пальцы смерти коснулись {player}, и теперь он стал частью вечной стужи. Это было нечто новое и оригинальное, как и сам {player}."
- "{player} решил уйти, замерзнув под покровом бескрайней полярной ночи. Завершив игру, он стал легендой, вечно сохраненной во льду."
- "Смерть от стихии льда – выбор {player}. Мы все ждали, что он выйдет на новый уровень, но не думали, что это будет таким холодным образом."


death by lightning:
- "Молния приземлилась, и {player} стал ее последней жертвой. Электрический финал – нечто по-настоящему зажигательное!"
- "В потоке молний {player} нашел свой последний путь к величию. Мы все ожидали, что его смерть будет впечатляющей, но не до такой степени!"
- "{player} решил встретить свой финал, притянутый к земле мощным разрядом молнии. Новый уровень адреналина – это точно."
- "Смерть от стихии молнии стала заключительным эпизодом в истории {player}. Кто бы мог подумать, что он предпочтет электрическую концовку?"


death by elemental:
- "{player} встретил свой финал в объятиях элементаля. Кажется, стихии решили внести свой вклад в его легендарное приключение."
- "Элементаль стал неотъемлемой частью истории {player}, завершив ее своим могущественным присутствием. Необычный, но стильный выход из игры!"
- "{player} решил испытать свою судьбу, встретив смерть в виде элементаля. Экстремально? Может быть. Классно? Определенно."
- "Смерть от элементаля – выбор настоящего викинга. {player} ушел, оставив нас с воспоминаниями о том, как стихии встретили его с открытыми объятиями."


death by tree:
- "Великий викинг {player} пал под ударом природы, будто его судьбу определяло падение древесного великана. Смерть, как последний акт в лесной симфонии."
- "От теней, опущенных падающим деревом, {player} прощается с этим миром. Это был неожиданный финал, словно пришествие лесного титана."
- "Великий викинг {player} ушел, сталкившись с натиском могучего ствола. Его смерть – как уход под тень падающего дерева, последний акт в легенде лесов."
- "{player} покидает этот мир, погибнув под тяжестью векового дерева. Это было необычное прощание, словно приговоренный к последнему танцу с природой."



death by pierce:
- "Великий викинг {player} пал от смертоносного объятия, будто его судьбу насаживали на острие выдающейся эпопеи. Кто бы мог подумать, что смерть бывает такой... проникновенной?"
- "От смертоносного объятия {player} ушел в тенях. Возможно, его судьбу насаживали на что-то, что предполагает лишь настоящий викинг. Интриги Вальхейма, даже в смерти."
- "Великий викинг {player} прощается с этим миром, словно его судьбу насаживают на что-то острое и впечатляющее. Видимо, смерть в Вальхалле – это нечто... заостренное."
- "{player} ушел, оставив этот мир, будто его судьбу насаживали на что-то острое и загадочное. Невероятное проникновение в иные миры, ведь таков путь великого викинга."


death by slash:
- "Великий викинг {player} столкнулся с разрубающим ударом, который положил конец его путешествию. Это было не просто разрубание судьбы, а настоящее искусство войны."
- "Смертоносный клинок в руках {player} разрубил его судьбу на части. Последнее разделение – как искусное произведение великого викинга."
- "Великий викинг {player} уходит под ударами, словно его судьбу разрубают на части. Это было неизбежное разделение, подчеркнутое войной и мечом."
- "{player} покидает этот мир, столкнувшись с разрубающим ударом. Его смерть – это как искусство, созданное мечом, разделение, которое останется в памяти."
- "Теперь Вальхалла знает, что {player} – не самый ловкий. И его останки это подтверждают очень наглядно."

death by blunt:
- "Великий викинг {player} ушел, погибнув от сокрушительных ударов, будто его судьбу формировали силы, оставляющие разломленный след в викингских сагах."
- "От разгромительных ударов, словно кулаки судьбы, {player} прощается с этим миром. Не каждый может выстоять перед такой разрушительной мощью."
- "Великий викинг {player} пал под молотом силы, будто его судьбу определяли удары, разгоняющие все мысли. Смерть, как громкий удар в тишине валькирий."
- "{player} покидает этот мир под ошеломляющими ударами. Это было не просто разломление судьбы, а настоящий викингский шторм, оставивший лишь разрушенные воспоминания."
- "Героический {player} думал, что его кости крепче стали. Удар показал, что кости — отличная начинка для земли."

death by physical:
- "Великий викинг {player} ушел, исчезнув под силой разрушительных атак, будто его судьбу выковывали в огне викингских битв."
- "От грозящих ударов, как будто кулаки воина судьбы, {player} прощается с этим миром. Это была буря стальных ударов и военных подвигов."
- "Великий викинг {player} пал под воздействием сил природы, словно его судьбу формировали удары, обрушивающиеся как булыжник с небес. Смерть, как вихрь стальных клинков."
- "{player} покидает этот мир, сталкиваясь с непрекращающимися испытаниями. Это было не просто разломление судьбы, а настоящая битва с весом стальных клинков."


death by gravity:
- "В отваге и славе {player} выбрал смерть от падения с высокой скалы – как настоящий викинг. Последний свой рейд в иные миры."
- "Викинг {player} ушел в великом стиле, решив опробовать свою удачу в падении с высоты. Падение, достойное саги!"
- "Последний поход {player} завершился падением с высокой скалы. Великолепный способ покинуть мир, достойный настоящего викинга."
- "{player} смело вступил в Вальгаллу, выбрав смерть от падения. Видимо, он решил устроить себе свой собственный викингский фестиваль в Асгарде."


death by drowning:
- "О, великий {player}, выбравший погружение в пучины. Даже в Асгарде мы обсуждаем твой выбор – такой мерзкий конец для великого викинга."
- "Судьба викинга {player} завершилась погружением в воды. Один, с иронией в голосе, встречает его в Вальгалле: 'Так это твой героический финал?'"
- "Викинг {player}, ты выбрал погружение в бездны. Один встречает тебя в послерейдовом мире: 'Кто бы мог подумать, что так можно закончить свой путь?'"
- "О, великий {player}, ты нашел свою участь в пучинах. Один, наблюдая сверху, говорит: 'Так вот к чему приводит твоя викингская смелость.'"


death by player:
- "Великий викинг {player} встретил свой конец от руки другого отважного воина, {enemy}. Его смерть стала последним актом в этой викингской саге."
- "{enemy}, другой великий викинг, стал исполнителем смертного приговора для {player}. Так заканчиваются легенды в мире Вальхейма."
- "Смерть от рук соратника, {enemy}, поставила точку в истории великого викинга {player}. В конце концов, даже викинги должны сталкиваться с судьбой."
- "Викинг {player} покинул этот мир, падая под ударами другого отважного воина, {enemy}. В Асгарде, возможно, их имена будут вместе воспеты в бессмертных скандинавских песнях."


death by creature:
- "Смерть пришла к {player} от рук жалкого создания, даже не заслуживающего внимания в Асгарде. Не каждый путь в Вальхаллу достоин великого викинга."
- "Великий викинг {player} ушел из этого мира, столкнувшись со слабым существом, недостойным даже упоминания в беседах о войнах Асгарда."
- "От рук ничтожного существа {enemy}, {player} покинул этот мир. Вероятно, Вальхалла не предназначена для тех, кто умирает подобным образом."
- "{enemy} – слабый представитель в мире Вальхейма, и все же именно от него {player} встретил свой последний час. Иногда даже слабые создания могут стать фатальными."



death by boss:
- "Великий викинг {player} встретил свой финал в битве с могучим врагом, {enemy}. Его смерть – лишь великолепный проход во Врата Вальхаллы."
- "{player} встретил свою участь в поединке с бесстрашным врагом, {enemy}. Наконец-то, путь в Вальхаллу открыт для великого викинга."
- "Смерть великого викинга {player} пришла от рук сильнейшего врага, {enemy}. Теперь его душа направляется в Асгард, где его подвиги будут воспеты."
- "Великий викинг {player} завершил свой путь, сразившись с непобедимым врагом, {enemy}. Его последний бой открыл врата Вальхаллы, ибо только великие достойны встречи с богами."

