Out_Wendigo:
  health: 0.41
  health per star: 0.41
  key_defeated_eikthyr:
   health: 0.75
   health per star: 0.55
   damage: 1.4
Out_BirchElder:
 Meadows:
  health: 1.4
  health per star: 0.7
  movement speed: 1.1
  attack speed: 1.2
  effect power:
    Regenerating: 0.5
  infusion:
   spirit: 0
   chaos: 0
  key_defeated_gdking:
   health: 2.6
 Plains:
  damage: 3
  health: 4
  movement speed: 1.2
  attack speed: 1.3
  effect power:
    Regenerating: 0.5
  infusion:
   spirit: 0
   chaos: 0
Out_Yeti:
  damage: 1
  health: 1
  health per star: 0.5
  effect power:
    Regenerating: 0.5
Out_VoidCultist:
  health: 0.5
  health per star: 0.5
Out_Apparition:
 Meadows:
  damage: 0.2
  damage per star: 0.05
  health: 2
  health per star: 1
 BlackForest:
  damage: 0.3
  damage per star: 0.05
  health: 3
  health per star: 1
 Swamp:
  damage: 0.4
  damage per star: 0.05
  health: 4
  health per star: 1
 Mountain:
  damage: 0.5
  damage per star: 0.05
  health: 5
  health per star: 1
 Plains:
  damage: 0.6
  damage per star: 0.05
  health: 6
  health per star: 1
 Mistlands:
  damage: 0.7
  damage per star: 0.05
  health: 7
  health per star: 1
 DeepNorth:
  damage: 0.8
  damage per star: 0.05
  health: 8
  health per star: 1
 Ashlands:
  damage: 0.8
  damage per star: 0.05
  health: 8
  health per star: 1