groups:
  MeadBase:
  - BarleyWineBase
  - MeadBaseEitrMinor
  - MeadBaseFrostResist
  - MeadBaseHealthMajor
  - MeadBaseHealthMedium
  - MeadBaseHealthMinor
  - MeadBasePoisonResist
  - MeadBaseStaminaLingering
  - MeadBaseStaminaMedium
  - MeadBaseStaminaMinor
  - MeadBaseTasty
  - MeadBaseLightningResist_TW
  - MeadBaseLingeringStaminaMinor_TW
  - MeadBaseLingeringStaminaMedium_TW
  - sm_base_greaterhealth
  - sm_base_greaterstamina
  - sm_base_exp
  - sm_base_speed
  - sm_base_skilldrain
  - sm_base_rested
  - sm_base_teleport
  - sm_base_warm
  - sm_base_fast_attack
  - sm_base_silent
  - sm_base_eitr
  CustomFood:
  - HoneyGlazedDeer
  - HoneyGlazedMeat
  - HoneyGlazedNeck
  - HoneyGlazedSpiderMeat
  - CookedSpiderMeat
  - CookedKrakenMeat
  - CookedEntrails
  - ElkJerky
  - LoxJerky_JH
  - SeekerJerky_JH
  - SpiderMeatSkewer_JH
  - HoneyGlazedLox
  - HoneyGlazedWolf
  - JellyGlazedHare
  - JellyGlazedSeeker
  - CookedYetiMeat_JH
#
all:
    floating: yes
    pickup: yes
# stuff floats in water; everything is pickable
Stackable:
    stack: 20
# all stackable items
DragonEgg:
    stack: 1
    weight: 200
AshenEgg_TW:
    stack: 1
    weight: 250
ArcticEgg_TW:
    stack: 1
    weight: 250
# eggs stack up to 3, and weigh considerably less
MeadBase:
    stack: 10
mmo_mead_minor:
    stack: 10
mmo_mead_med:
    stack: 10
mmo_mead_greater:
    stack: 10
Food:
    stack: 10
CustomFood:
    stack: 10