name: ArmorWolfLegs
clonePrefabName: 
craftingStation: $piece_forge
minStationLevel: 2
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- Silver:20:5:True
- WolfPelt:8:4:True
- WolfFang:4:2:True
