1:
  success: 80
2:
  success: 75
3:
  success: 70
4:
  success: 60
5:
  success: 55
6:
  success: 50
7:
  success: 40
8:
  success: 35
9:
  success: 30
10:
  success: 26
11:
  success: 22
12:
  success: 18
13:
  success: 14
14:
  success: 10
15:
  success: 8
16:
  success: 6
17:
  success: 5
18:
  success: 4
19:
  success: 2
