1:
  damage_percentage: 2
2:
  damage_percentage: 4
3:
  damage_percentage: 6
4:
  damage_percentage: 8
5:
  damage_percentage: 10
6:
  damage_percentage: 12
7:
  damage_percentage: 16
8:
  damage_percentage: 20
9:
  damage_percentage: 24
10:
  damage_percentage: 28
11:
  damage_percentage: 32
12:
  damage_percentage: 36
13:
  damage_percentage: 40
14:
  damage_percentage: 45
15:
  damage_percentage: 50
16:
  damage_percentage: 55
17:
  damage_percentage: 60
18:
  damage_percentage: 70
19:
  damage_percentage: 85
20:
  damage_percentage: 100
