enchantment_success: "Усовершенствование успешно!\n($1 +$2 -> +$3)"
enchantment_fail_destroyed: "Усовершенствование не удалось!\n($1 уничтожено)"
enchantment_fail_leveldown: "Усовершенствование не удалось!\n($1 +$2 -> -$3)"
enchantment_fail_nochange: "Усовершенствование не удалось!\n($1 +$2)"
enchantment_cannotbe: "Этот предмет нельзя усовершенствовать"
enchantment_nomaterials: "У вас недостаточно материалов для усовершенствования этого предмета"
enchantment_bonusespercentdamage: "Увеличение урона"
enchantment_bonusespercentarmor: "Увеличение брони"
enchantment_chance: "Шанс усовершенствования"
enchantment_maxedout: "Усовершенствование достигло максимума"
enchantment_increasedwithenchantment: "Увеличено с помощью усовершенствования"
enchantment_canbeenchantedwith: "Может быть усовершенствовано с"
enchantment_enchant: "Усовершенствовать"
enchantment_menu: "Меню усовершенствования"
enchantment_cancel: "Отмена"
enchantment_additionalstats: "Дополнительные характеристики"
enchantment_selectanitem: "Выберите предмет"
enchantment_noenchantitems: "Нет предметов для усовершенствования"
enchantment_chopdamage: "Урон от рубки"
enchantment_truedamage: "Истинный урон"
enchantment_pickaxedamage: "Урон от кирки"
enchantment_ok: "OK"
enchantment_usebless: "Использовать благословение"
enchantment_header: "Усовершенствование предмета"
enchantment_failedenchantments: "Неудачные усовершенствования"
enchantment_holdshift: "Удерживайте [<color=yellow><b>L. Shift</b></color>], чтобы показать неудачные усовершенствования"
kg_enchantment_scrollstation: "Станция усовершенствования свитков"
kg_enchantment_scrollstation_description: "Позволяет создавать свитки усовершенствования"
kg_enchantscroll_weapon_F: "Свиток усовершенствования: Оружие (F)"
kg_enchantscroll_weapon_D: "Свиток усовершенствования: Оружие (D)"
kg_enchantscroll_weapon_C: "Свиток усовершенствования: Оружие (C)"
kg_enchantscroll_weapon_B: "Свиток усовершенствования: Оружие (B)"
kg_enchantscroll_weapon_A: "Свиток усовершенствования: Оружие (A)"
kg_enchantscroll_weapon_S: "Свиток усовершенствования: Оружие (S)"
kg_enchantscroll_armor_F: "Свиток усовершенствования: Броня (F)"
kg_enchantscroll_armor_D: "Свиток усовершенствования: Броня (D)"
kg_enchantscroll_armor_C: "Свиток усовершенствования: Броня (C)"
kg_enchantscroll_armor_B: "Свиток усовершенствования: Броня (B)"
kg_enchantscroll_armor_A: "Свиток усовершенствования: Броня (A)"
kg_enchantscroll_armor_S: "Свиток усовершенствования: Броня (S)"
kg_enchantscroll_weapon_blessed_F: "Благословенный свиток усовершенствования: Оружие (F)"
kg_enchantscroll_weapon_blessed_D: "Благословенный свиток усовершенствования: Оружие (D)"
kg_enchantscroll_weapon_blessed_C: "Благословенный свиток усовершенствования: Оружие (C)"
kg_enchantscroll_weapon_blessed_B: "Благословенный свиток усовершенствования: Оружие (B)"
kg_enchantscroll_weapon_blessed_A: "Благословенный свиток усовершенствования: Оружие (A)"
kg_enchantscroll_weapon_blessed_S: "Благословенный свиток усовершенствования: Оружие (S)"
kg_enchantscroll_armor_blessed_F: "Благословенный свиток усовершенствования: Броня (F)"
kg_enchantscroll_armor_blessed_D: "Благословенный свиток усовершенствования: Броня (D)"
kg_enchantscroll_armor_blessed_C: "Благословенный свиток усовершенствования: Броня (C)"
kg_enchantscroll_armor_blessed_B: "Благословенный свиток усовершенствования: Броня (B)"
kg_enchantscroll_armor_blessed_A: "Благословенный свиток усовершенствования: Броня (A)"
kg_enchantscroll_armor_blessed_S: "Благословенный свиток усовершенствования: Броня (S)"
kg_enchantscroll_weapon_description: "Используется для усовершенствования оружия с одинаковым требованием уровня"
kg_enchantscroll_armor_description: "Используется для усовершенствования брони с одинаковым требованием уровня"
kg_enchantscroll_weapon_blessed_description: "Используется для усовершенствования оружия с одинаковым требованием уровня. <color=green>Сохраняет оружие от уничтожения или понижения уровня в случае неудачи.</color>"
kg_enchantscroll_armor_blessed_description: "Используется для усовершенствования брони с одинаковым требованием уровня. <color=green>Сохраняет броню от уничтожения или понижения уровня в случае неудачи.</color>"
skill_1254459142: "Усовершенствование"
skilldesc_kg_Enchantment: "Увеличивает шанс успешного усовершенствования"
enchantment_requiresskilllevel: "Требуется уровень навыка усовершенствования: $1"
enchantment_additionalchance: "бонус навыка"
enchantment_skill_scroll: "Источник навыка усовершенствования"
enchantment_skill_scroll_use: "Получить опыт навыка усовершенствования"
enchantment_attackspeed: "Скорость атаки"
enchantment_slashwave: "Волна удара"
enchantment_searchbyname: "Поиск по имени..."
enchantment_defaultstats_weapon: "Стандартные характеристики оружия"
enchantment_defaultstats_armor: "Стандартные характеристики брони"
enchantment_defaultchances: "Стандартные шансы усовершенствования"
enchantment_info_reqs: "Требования"
enchantment_info_stats: "Характеристики"
enchantment_info_chances: "Шансы"
enchantment_info: "Информация"
enchantment_enablehotbarvfx: "Включить визуальные эффекты на панели быстрого доступа"
enchantment_enablemainvfx: "Включить основные визуальные эффекты"
enchantment_enablewingsvfx: "Включить визуальные эффекты крыльев"
enchantment_enableauravfx: "Включить визуальные эффекты ауры"
enchantment_enableinventoryvfx: "Включить визуальные эффекты в инвентаре"
enchantment_settings_reset: "Сбросить все"
enchantment_enchantment: "Усовершенствование"
enchantment_enchantspeed: "Скорость усовершенствования"
enchantment_notification_success: "<color=cyan>$1</color> успешно усовершенствовал <color=yellow>$2</color> (+$3 -> +$4)"
enchantment_notification_fail: "<color=cyan>$1</color> не смог усовершенствовать <color=yellow>$2</color> (+$3 -> +$4)"
enchantment_notification_fail_destroyed: "<color=cyan>$1</color> не смог усовершенствовать <color=yellow>$2</color> (уничтожено)"
enchantment_notification_fail_topic: "Неудачное усовершенствование"
enchantment_notification_success_topic: "Успешное усовершенствование"
enchantment_notificationfilter: "Показывать уведомления"
enchantment_notificationduration: "Длительность уведомлений"
enchantment_putinlinetocombine: "Разместите свитки в форме $1 в своем инвентаре, чтобы объединить их в свиток более высокого уровня"