# Creatures
## Nameplates for Creatures
# dir \profiles\..\BepInEx\plugins\OdinPlus-OdinHorse

horse_odin: "Лошадь"
horse_offspring: "Лошадиное потомство"

# Materials
## Components, miscs and materials

horse_hide: "Лошадиная шкура"
horse_hide_desc: "Шкура с лошади"

trophy_horse: "Лошадиный трофей"
trophy_horse_desc: "Трофей за охоту на лошадь"

# Items
## Item names and descriptions

item_horse_saddle: "Лошадиное седло"
item_horse_saddle_desc: "Вам понадобится седло чтобы оседлать прирученную лошадь"

horse_saddle: "Лошадиное седло"
horse_saddle_desc: "Вам понадобится седло чтобы оседлать прирученную лошадь"

horsesaddle_onhorse: "Седло"

horse_helmet: "Шлем из лошадиного трофея"
horse_helmet_desc: "Трофейный шлем сделанный из трофейной лошадиной головы"

horse_cape: "Лошадиный плаш"
horse_cape_desc: "Плащ сделанный из лошадиной кожи"

horseaker: "Хорсэйкер"
horseaker_desc: "Двуручный боевой топор с железной эмблемой в виде лошадиной головы"

ArmorHorseClothHelmet_T1: "Капюшон Лесничего"
ArmorHorseClothHelmet_T1_desc: "Мягкий, но толстый предмет из лошадиной кожи, отлично подходит охотникам"

ArmorHorseClothChest_T1: "Нагрудник Лесничего"
ArmorHorseClothChest_T1_desc: "Мягкий, но толстый предмет из лошадиной кожи, отлично подходит охотникам"

ArmorHorseClothLegs_T1: "Штаны Лесничего"
ArmorHorseClothLegs_T1_desc: "Мягкий, но толстый предмет из лошадиной кожи, отлично подходит охотникам"

ArmorHorseClothHelmet_T2: "Маска Драпмадра"
ArmorHorseClothHelmet_T2_desc: "Мягкий, но толстый предмет из лошадиной кожи, улучшенный кусками кожи и кусками обогащенной руды"

ArmorHorseClothChest_T2: "Нагрудник Драпмадра"
ArmorHorseClothChest_T2_desc: "Мягкий, но толстый предмет из лошадиной кожи, улучшенный кусками кожи и кусками обогащенной руды"

ArmorHorseClothLegs_T2: "Штаны Драпмадра"
ArmorHorseClothLegs_T2_desc: "Мягкий, но толстый предмет из лошадиной кожи, улучшенный кусками кожи и кусками обогащенной руды"

horseset_t1: "Эффект Лесничего"
horseset_t1_desc: "Лесничие были легендарными охотниками, жившие в лесу, охотившиеся на животных и воров. Они говорили что они были сыновьями лесного бога Скогара."

horseset_t2: "Эффект Драпмадра"
horseset_t2_desc: "Драпмадр был злобным убийцей, цель которого была убивать безовсякой причины. Его описывали как безжалостного, беспринципного и благословенным Локи."

# Foods
## Consumables like meats and soups

horse_meat: "Лошадиное мясо"
horse_meat_desc: "Мясо из лошади"

horse_skewer: "Шашлык из лошадины"
horse_skewer_desc: "Шашлык из лошадиного мяса с вкусными добавками"

horse_soup: "Густой суп"
horse_soup_desc: "Суп из лошадиного мяса со специальными ингредиентами"

horse_sticks: "Тёмные Франкфуртские сосиски"
horse_sticks_desc: "Сосиски из лошадиного мяса"

# Pieces
## Buildable components

pin_cart: "Лошадиная повозка"
horse_cart: "Лошадиная повозка"

horse_rug: "Коврик из конской шкуры"
horse_rug_desc: "Коврик сделанный из конской шкуры"

horse_chair: "Horsie"
horse_chair_desc: "Забавный стул"