- Items:
  - ArmorPlateCape
  Stats:
    1:
      armor_percentage: 2
    2:
      armor_percentage: 3
    3:
      armor_percentage: 4
    4:
      armor_percentage: 5
    5:
      armor_percentage: 6
      resistance_poison: Resistant
    6:
      armor_percentage: 7
      resistance_poison: Resistant
    7:
      armor_percentage: 9
      resistance_poison: Resistant
    8:
      armor_percentage: 11
      resistance_poison: Resistant
    9:
      armor_percentage: 13
      resistance_poison: Resistant
    10:
      armor_percentage: 15
      resistance_poison: Resistant
    11:
      armor_percentage: 17
      resistance_poison: Resistant
    12:
      armor_percentage: 19
      resistance_poison: Resistant
    13:
      armor_percentage: 22
      resistance_poison: Resistant
    14:
      armor_percentage: 25
      resistance_poison: Resistant
    15:
      armor_percentage: 28
      resistance_poison: VeryResistant
    16:
      armor_percentage: 31
      resistance_poison: VeryResistant
    17:
      armor_percentage: 35
      resistance_poison: VeryResistant
    18:
      armor_percentage: 39
      resistance_poison: VeryResistant
    19:
      armor_percentage: 44
      resistance_poison: VeryResistant
    20:
      armor_percentage: 50
      resistance_poison: VeryResistant