name: kg_EnchantScroll_Armor_A
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- GoblinScraps_TW:5:0:True
- SerpentScale:5:0:True
- InfusedCrystal_JH:2:0:True
- TrophyGoblin:1:0:True
