name: kg_EnchantScroll_Armor_F
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- FoxPelt_TW:5:0:True
- Flint:5:0:True
- InfusedCrystal_JH:2:0:True
- TrophyFox_TW:1:0:True
