name: kg_EnchantScroll_Weapon_D
clonePrefabName: 
craftingStation: Scroll Station
minStationLevel: 1
maxStationLevelCap: 
repairStation: 
amount: 1
disabled: false
requireOnlyOneIngredient: false
reqs:
- BlackBearPelt_TW:5:0:True
- GreydwarfEye:5:0:True
- InfusedCrystal_JH:2:0:True
- TrophyGreydwarf:1:0:True
