# Items
## Item names and descriptions
# dir \profiles\..\BepInEx\plugins\OdinPlus-OdinCampsite

item_campsite: "Ресурсы для кемпинга"
item_campsite_desc: "Базовый набор предметов для кемпинга, которые нужны для строительства лагеря."

# Pieces
## Buildable components

piece_campsite_firepit: "Маленький костёр"
piece_campsite_firepit_desc: "Этого уютного костра хватит только отогреть руки."

piece_sleepingbag: "Спальный мешок"
piece_sleepingbag_desc: "Для любителей нескучных приключений. Спите под звездами, где бы вы ни находились."

campsite_smalltent: "Маленькая палатка"
campsite_smalltent_desc: "Для опытных искателей приключений. Защитите свое лицо от снега и дождя с помощью этой простой палатки."

campsite_bigtent: "Большая палатка"
campsite_bigtent_desc: "Для любителей приключений, проверенных временем. С помощью этой просторной палатки можно построить небольшую базу для форпоста."