creatureGender:
  default: n

genderedCreatureTranslations:
  n: '[{effect} ][{infusion} ]{name}[ {affix}]'

genderedTranslations:

translations:
  # effect
  Aggressive: Агрессивный
  Armored: Бронированный
  Curious: Любопытный
  Quick: Шустрый
  Regenerating: Регенерирующий
  Splitting: Почкующийся
  # infusion
  Fire: "<color=orange>Огненный</color>"
  Frost: "<color=#7CB9E8>Ледяной</color>"
  Lightning: "<color=#BF00FF>Электрический</color>"
  Chaos: '<color=brown>Хаотический</color>'
  Spirit: "<color=red>Вампирический</color>"
  Poison: "<color=#54FB0D>Ядовитый</color>"
  # affix
  Reflective: Спектральный Отражатель
  Shielded: Скользящий на Грани
  Mending: Мистический Целитель
  Summoner: Прародитель
  Elementalist: Элементалист
  Enraged: Яростный
  Twin: Парный Титан
  
  CreatureSectorLevelIncrease: "Существа рядом с {player} усиливаются, чтобы отомстить за гибель своих сородичей."
  MinimapSectorLevel: 'Уровень сектора: {level}'
  ConfigEditorSave: "Сохранить и применить"
  ConfigEditorApplyNoSave: "Применить без сохранения"
  ConfigEditorDiscard: "Отменить и закрыть"
  Edit Creature YAML config: 'Редактировать YAML конфиг существ'
  Edit Item YAML config: 'Редактировать YAML конфиг предметов'
  SummonerEikthyr: '{boss} призвал {number} грейдворфа себе на помощь'
  SummonerElder: '{boss} призвал грейдворфа-дикоря себе на помощь'
  SummonerBonemass: '{boss} призвала {number} элитных Драугов  себе на помощь'
  SummonerModer: '{boss} призвала себе на помощь {number} Дрейков'
  SummonerYagluth: '{boss} призвал Фулинг Берсерка себе на помощь'
  SummonerQueen: '{boss} призвала {number} Искателья себе на помощь'

enumTranslations:
  Toggle:
    On: On
    Off: Off
  Difficulty:
    Custom: Custom
    Very_easy: Very easy
    Easy: Easy
    Medium: Medium
    Hard: Hard
    Very_hard: Very hard
    Insane: Insane
  CreatureSectorAnnouncementScope:
    Local: Local
    Global: Global
    Off: Off
  LootSystem:
    Vanilla: Vanilla
    Linear: Linear
    CalculateChance: Calculate chance
    CalculateAmount: Calculate amount
  VisualLevelIndicator:
    Off: Off
    On: On
    BossesOff: Off for Bosses
    CreaturesOff: Off for Creatures
  AllowedConsoleCommands:
    CreatureCommands: Creature Commands
    InformationCommands: Information Commands
    None: None
  VisualExtraEffectIndicator:
    Color: Color
    Text: Text
    Both: Color and Text
  DifficultySecondFactor:
    None: None
    Age_of_world: Use Age of World
    Distance: Use Distance from Spawn
    BossesKilled: Use Number of Bosses killed
  SpawnLevel:
    None: None
    One: One
    Two: Two
    Three: Three
    Four: Four
    Five: Five
  CreatureSectorWorldLevel:
    Disabled: Disabled
    None: None
    One: One
    Two: Two
    Three: Three
    Four: Four
    Five: Five
    Six: Six

settingGroups:
  General: General
  Creatures: Creatures
  Loot: Loot
  Bosses: Bosses
  Distance from Spawn: Distance from Spawn
  Age of world: Age of world
  Custom level chances: Custom level chances
  Creature Affix chances: Creature Affix chances
  Creature Infusion chances: Creature Infusion chances
  Boss Affix chances: Boss Affix chances
  Boss Affix power: Boss Affix power

settings:
  Lock Configuration:
    desc: The configuration is locked and may not be changed by clients. Only active for servers.
  Use creature configuration yaml:
    desc: Reads the CreatureConfig.yml file if present. Configuration done via the YAML file will override the same settings done via the default configuration file. For everything not configured in the YAML file, the default configuration file will still be used.
  Use item configuration yaml:
    desc: Reads the ItemConfig.yml file if present. Configuration done via the YAML file will override the same settings done via the default configuration file. For everything not configured in the YAML file, the default configuration file will still be used.
  nexusID:
    desc: Nexus mod ID for updates.
  HP increase per player in multiplayer (percentage):
    desc: Health increase per player in multiplayer in percent.
  DMG increase per player in multiplayer (percentage):
    desc: Damage increase per player in multiplayer in percent.
  Minimum player count for multiplayer scaling:
    desc: Sets the minimum player count for multiplayer games.
  Maximum player count for multiplayer scaling:
    desc: Sets the maximum player count for multiplayer games.
  Player count to be added to the actual player count for multiplayer scaling (0 is disabled):
    desc: Adds the defined number of players to the actual player count for multiplayer scaling.
  Multiplayer scaling per player range (0 is unlimited):
    desc: Range that other players have to be in in order to count towards the multiplayer scaling. Has no effect, if the fixed player count is set to something else than 0.
  Nameplate display on mouseover range:
    desc: Maximum distance for the nameplate to be shown on mouseover.
  Visual indicators for level:
    desc: Can be used to turn off visual indicators for the targets level, e.g. their stars or color.
  Console commands allowed to be used by users on a server:
    desc: Sets the CLLC commands that users on a server can use. Server admins can always use all commands. Has no effect, if the configuration is unlocked (for obvious reasons).
  Detailed damage log:
    desc: Enables detailed damage logging for each hit.
  Difficulty:
    desc: Sets the level up chances of all creatures.
  Second factor:
    desc: Change the second factor used to calculate the level up chances.
  Display circles on the map for distance from spawn option:
    desc: Display circles on the map for distance from spawn option.
  Creatures can spawn with special effects:
    desc: Creatures can spawn with special effects, making them a lot more difficult to kill.
  Visual indicator for special effects:
    desc: Changes the way the visual indicator for creatures extra effects is displayed.
  Creatures can spawn with elemental infusions:
    desc: Creatures can spawn with elemental infusions, making them a lot more difficult to kill.
  Add the infusion to the creatures name:
    desc: Creatures with elemental infusions have the elemental infusion added to their name.
  Brightness for the elemental infusions visual indicator (percentage):
    desc: Sets the brightness for the flames visual effect of elemental infused creatures.
  Minimum stars:
    desc: Sets the minimum stars for all creatures. Does not affect custom difficulty.
  Maximum stars:
    desc: Sets the maximum stars for all creatures. Does not affect custom difficulty.
  Time until creatures in dungeons respawn in minutes (0 means disabled, 30 is one ingame day):
    desc: Time until creatures in dungeons respawn in minutes (0 = disabled, 30 = one ingame day).
  Time until creatures in camps respawn in minutes (0 means disabled, 30 is one ingame day):
    desc: Time until creatures in camps respawn in minutes (0 = disabled, 30 = one ingame day).
  Creature size increase per star (percentage):
    desc: Increases the size of creatures per star.
  Increase creature size even in dungeons (where they might get stuck):
    desc: If creature size will be increased in dungeons as well, where they might get stuck if they get too big.
  Base health for creatures (percentage):
    desc: Base health for creatures in percentage.
  Health gained per star for creatures (percentage):
    desc: Health gained per star for creatures in percentage.
  Base damage for creatures (percentage):
    desc: Base damage for creatures in percentage.
  Damage gained per star for creatures (percentage):
    desc: Damage gained per star for creatures in percentage.
  Base movement speed for creatures (percentage):
    desc: Base movement speed for creatures in percentage.
  Base attack speed for creatures (percentage):
    desc: Base attack speed for creatures in percentage.
  World level required to enable creature sectors:
    desc: Minimum world level for creature sectors to become active.
  Time until each creature sector is reset (0 is no reset):
    desc: Time that needs to pass before a creature sectors bonus level is reset in minutes (0 = disabled, 30 = one ingame day).
  Kills required in a sector for each bonus level:
    desc: Creature kills required in the same sector for creatures to gain bonus level.
  Sets the scope for creature sector level up announcements:
    desc: Sets the scope for the creature sector level up announcements.
  Duration of the map ping for creature sector level ups in seconds (0 is disabled):
    desc: Pings the map on creature sector level ups. Time is in seconds. 0 means disabled.
  Displays the current creature sector level on the minimap:
    desc: Displays the current creature sector level on the minimap.
  Loot system to be used:
    desc: |
      Sets the loot system to be used.
      Vanilla disables the loot system from this mod completely.
      Linear: Dropped items are multiplied with the creatures level.
      Calculate chance: A boar has a 50% chance to drop 2 meat, it will either drop 2 or none.
      Calculate amount: A boar has a 50% chance to drop 2 meat, it will always drop 1.
  Chance for additional loot per star for creatures:
    desc: Chance for additional loot per star for creatures.
  Chance for additional loot per star for bosses:
    desc: Chance for additional loot per star for bosses.
  Multiplier for dropped creature items:
    desc: Multiplies the items dropped by all creatures.
  Multiplier for dropped boss items:
    desc: Multiplies the items dropped by all bosses.
  Creatures can drop multiple trophies:
    desc: If creatures can drop multiple trophies.
  Bosses can drop multiple trophies:
    desc: If bosses can drop multiple trophies.
  Drop multiplier for passive creatures (like Seagulls and Crows):
    desc: Multiplies the items dropped by all passive creatures like Crows and Seagulls.
  Time until items in dungeons respawn in minutes (0 means disabled, 30 is one ingame day):
    desc: Time until items in dungeons respawn in minutes (0 = disabled, 30 = one ingame day).
  Bosses can spawn with special effects:
    desc: Bosses can spawn with special effects, making them a lot more difficult to kill.
  Use creature level chances for bosses:
    desc: On means that the level up chances for creatures are used for bosses as well. Otherwise, the custom level chances for bosses will be used.
  Star chances for bosses (percentages):
    desc: Level chances for bosses. Start with 1 star, from left to right, as many stars as you want. 0 star chance will be automatically calculated from the remainder.
  Boss size increase per star (percentage):
    desc: Increases the size of bosses per star.
  Health gained per star for bosses (percentage):
    desc: Health gained per star for bosses in percentage.
  Damage gained per star for bosses (percentage):
    desc: Damage gained per star for bosses in percentage.
  World level {level} start (days):
    desc: Days needed to pass before your world gets to world level {level}.
  Distance from spawn for level {level} start:
    desc: Distance from spawn for level {level} start. Radius for a default world is 10500.
  Chances for stars at world level {level} (percent):
    desc: 'Chances for stars at world level {level} in percent. As many stars as you want from left to right, comma separated. Start with 1 star. 0 star chance will be automatically calculated using the remainder. Example: 30, 5.5, 2.25, 5, 10, 10, 3'
  Chance for {effect} effect to spawn (percentage):
    desc: Chance for {effect} effect creatures to spawn (percentage).
  Chance for {infusionDescription} infusion to spawn (percentage):
    desc: Chance for {infusionDescription} infusion creatures to spawn (percentage).
  Multiplier for infusion chances per star:
    desc: Multiplier applied to base chances for infusions to spawn according to the number of stars of the creature. Chances for every amount of stars, from left to right, comma separated. Start with 0 stars. Defaults to 1.
  Chance for {affix} affix to spawn (percentage):
    desc: Chance for {affix} affix bosses to spawn (percentage).
  Reflective base damage:
    desc: Base damage per hit for the Reflective boss affix.
  Shielded damage reduction (percentage):
    desc: Damage reduction for ammo in percent for the Shielded boss affix.
  Mending healing factor:
    desc: Multiplier for the Mending boss affix.
  Number of summons for Summoners:
    desc: The number of summoning events over the course of the fight for the Summoner boss affix.
  Elementalist damage increase (percentage):
    desc: Elemental damage increase for Elementalist boss affix.
  Enraged damage increase (percentage):
    desc: Phyiscal damage increase for Enraged boss affix.
  Twin damage and health (percentage):
    desc: Health and damage for Twin boss affix.
